services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql_data:/var/opt/mssql

  backend:
    image: itsamil/hotel-backend:latest
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=Hotel_DB;User Id=sa;Password=${SA_PASSWORD};Encrypt=True;TrustServerCertificate=True;"
      Jwt__Key: "${JWT_KEY}"
      Jwt__Issuer: "hotel-api"
      Jwt__Audience: "hotel-client"
      Cloudinary__CloudName: "${CLOUDINARY_CLOUD_NAME}"
      Cloudinary__ApiKey: "${CLOUDINARY_API_KEY}"
      Cloudinary__ApiSecret: "${CLOUDINARY_API_SECRET}"
      Seed__AdminEmail: "${SEED_ADMIN_EMAIL}"
      Seed__AdminPassword: "${SEED_ADMIN_PASSWORD}"

  frontend:
    image: itsamil/hotel-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mssql_data: